language: swift
os: osx
osx_image: xcode10.2
xcode_scheme: TaskemFoundationTests
xcode_project: Taskem
xcode_destination: platform=iOS Simulator,OS=12.3,name=iPhone X

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME